base BookController methods added
EruAI-Mutex-Team1/fullstack-library pull request #24
Opened 2024-09-16 23:46 UTC by Fatihcagdas100

add-ons will be added later

2024-09-16 23:47 UTC, Fatihcagdas100 commented
Kodda bir çok hatalar var biliyorum.
İskelet böyle mi
ve kod hakkında yardımcı olabileceğin bir yer var mı

2024-09-18 11:09 UTC, turkerkiv requested changes
İyi duruyor birkaç eksik ve önerim var.
- return oklerde şimdilik böyle kalsın ama onları dtoya çevirip sadece ne lazımsa onu göndericez ilerde birkaç gün sonra.
- Borrowedbooksta da bir id almak lazım userid olacak çünkü kimin ödünç aldığı kitaplarsa ona göre getirecez sadece. Bir de listelerken hepsini listelemicez. Yani şöyle olacak borrowrequests içinden ispending olmayanların isapproved olanların useridsi gelen useridye eşit olan şeklinde. yani bookrepodan değil de bookrequestrepodan.
- Getbooksbyauthorda da author name almak yerine useridsini almalıyız ki benzersiz olsun yoksa aynı isimli authorlarda sıkıntı çıkar.  
- addpagetobook kısmında book.pages.add diyip page i eklemişsin ona gerek yok zaten repositoryde create page diyince database e saklanır. pages ı çekerken de o da gelir zaten. yani bookrepo updatebook demek yerine pagerepo create page demek lazım.
- programcs değiştirmen iyi olmuş unutmuştum

2024-09-20 08:39 UTC, turkerkiv requested changes
- borrowedbooksta şu an pending false ve confirmed olanları getiriyoruz ama döndürülmüş olanlar da gelir o yüzden ekstra koşul eklemek lazım döndürülmeyenler diye.
- zaten çoğu bitmiş o yüzden dto eklemeye başlayalım bence. Return ok diyoruz ya o komple bir entity döndürmek yerine sadece gerekli propertyleri yani değişkenleri döndürücez. Bunun için dto klasörü içine ne zaman gerekirse bir class açarsın ismi DTO ile biten. içine ilgili entity içinden hangisi gerekiyorsa onu koy sadece. değişken isimleri aynı olsun. bu şekilde daha sağlıklı ve her yerde kullanılıyor. Aynı zamanda sadece döndürürken değil parametre olarak beklerken de entity yerine bir dto beklemek lazım çünkü mesela page beklerken karşı taraf page gönderecek ya idsini veya gerekmeyen bir şeyi girmek zorunda kalmasın falan.

2024-09-21 15:55 UTC, turkerkiv requested changes
Eline sağlık.
Auto mapper kullanmayacaktım kafanız karışmasın fazla diye. ilk önce kötü şekliyle yapıp sonra refactor yani kodu güzelleştirmeyi yapmak ilk başlarda daha iyi.
istersen automapper ı kaldır çünkü birkaç hata var direkt kendin new Dto diyerek object oluştur daha sonra onu ekleriz. dto listesi gereken yerlerde de select() diye linq methodunu kullanabilirsin.

2024-09-26 15:59 UTC, turkerkiv approved these changes

2024-09-26 15:59 UTC, merged